image: mcr.microsoft.com/dotnet/sdk:7.0

pipelines:
  default:
    - parallel:
        - step:
            name: Build and No Test
            caches:
              - dotnetcore
            script:
              - export SOLUTION_NAME=xxx
              - export CONFIGURATION=Debug
              - export PATH="$PATH:/root/.dotnet/tools"
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - apt-get update
              - apt-get install --yes --force-yes
              - apt-get install -y openjdk-11-jre
              - cd xxx-xxx
              - dotnet tool install --global dotnet-sonarscanner
              - dotnet sonarscanner begin /k:"xxx_xxx" /d:"sonar.host.url=https://sonarcloud.io"  /d:sonar.login="${SONAR_TOKEN}" /o:"xxx"
              - dotnet build ${SOLUTION_NAME}.sln
              - dotnet sonarscanner end /d:"sonar.login=${SONAR_TOKEN}"
        
  branches:
    master:
    - parallel:
        - step:
            name: Build and No Test
            caches:
              - dotnetcore
            script:
              - export SOLUTION_NAME=xxx
              - export CONFIGURATION=Debug
              - export PATH="$PATH:/root/.dotnet/tools"
              - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
              - apt-get update
              - apt-get install --yes --force-yes
              - apt-get install -y openjdk-11-jre
              - cd xxx-xxx
              - dotnet tool install --global dotnet-sonarscanner
              - dotnet sonarscanner begin /k:"xxx_xxx" /d:"sonar.host.url=https://sonarcloud.io"  /d:sonar.login="${SONAR_TOKEN}" /o:"xxx"
              - dotnet build ${SOLUTION_NAME}.sln
              - dotnet sonarscanner end /d:"sonar.login=${SONAR_TOKEN}"